// Category weights and context words for scoring
// Adjust weights as you gather user feedback

export const CATEGORY_WEIGHTS: {
  [category: string]: { [keywordOrEntity: string]: number }
} = {
  'Animals': {
    'animal': 1,
    'dog': 0.9,
    'cat': 0.9,
    'pet': 0.8,
    'wildlife': 0.7,
    'zoo': 0.6,
    'species': 0.5,
  },
  'Nature': {
    'nature': 1,
    'tree': 0.9,
    'forest': 0.9,
    'mountain': 0.8,
    'river': 0.7,
    'landscape': 0.7,
    'outdoors': 0.6,
    'flower': 0.6,
    'park': 0.5,
  },
  'Products': {
    'product': 1,
    'brand': 0.8,
    'item': 0.7,
    'price': 0.7,
    'buy': 0.6,
    'purchase': 0.6,
    'review': 0.5,
    'store': 0.5,
  },
  'Art': {
    'art': 1,
    'painting': 0.9,
    'drawing': 0.9,
    'sketch': 0.9,
    'sculpture': 0.8,
    'gallery': 0.8,
    'museum': 0.8,
    'design': 0.8,
    'illustration': 0.8,
    'creative': 0.7,
    'inspiration': 0.7,
    'idea': 0.7,
    'logo': 0.7,
    'concept': 0.7,
    'moodboard': 0.6,
    'canvas': 0.6,
    'color': 0.6,
    'print': 0.6,
    'exhibit': 0.5,
    'artist': 0.5,
    'modern': 0.5,
    'abstract': 0.5,
    'portrait': 0.5,
    'landscape': 0.5,
    'installation': 0.5,
    'visual': 0.5,
  },
  'Screenshots': {
    'screenshot': 1,
    'screen': 0.9,
    'capture': 0.9,
    'window': 0.8,
    'desktop': 0.8,
    'app': 0.8,
    'phone': 0.7,
    'mobile': 0.7,
    'device': 0.7,
    'display': 0.7,
    'image': 0.6,
    'snapshot': 0.6,
    'record': 0.6,
    'save': 0.5,
    'share': 0.5,
    'notification': 0.5,
    'toolbar': 0.5,
    'status': 0.5,
    'UI': 0.5,
    'interface': 0.5,
    'button': 0.5,
    'icon': 0.5,
  },
  'Receipts & Invoices': {
    'receipt': 1,
    'invoice': 1,
    'payment': 0.9,
    'total': 0.8,
    'amount': 0.7,
    'transaction': 0.7,
    'order': 0.6,
    'bill': 0.6,
    'date': 0.5,
    '$': 0.5,
  },
  'Recipes': {
    'recipe': 1,
    'ingredients': 0.9,
    'instructions': 0.8,
    'cook': 0.8,
    'bake': 0.7,
    'food': 0.7,
    'kitchen': 0.6,
    'dish': 0.5,
    'meal': 0.5,
  },
  'Documents': {
    'document': 1,
    'pdf': 0.9,
    'file': 0.8,
    'report': 0.7,
    'letter': 0.7,
    'form': 0.6,
    'contract': 0.6,
    'page': 0.5,
  },
  'Social Media': {
    'social': 1,
    'media': 1,
    'post': 0.9,
    'profile': 0.8,
    'comment': 0.7,
    'like': 0.6,
    'share': 0.6,
    'tweet': 0.5,
    'story': 0.5,
  },
  'Inspiration & Ideas': {
    'inspiration': 1,
    'idea': 1,
    'logo': 0.9,
    'design': 0.8,
    'art': 0.7,
    'sketch': 0.7,
    'concept': 0.6,
    'moodboard': 0.5,
    'creative': 0.5,
  },
  'Travel': {
    'travel': 1,
    'trip': 0.9,
    'flight': 0.8,
    'hotel': 0.8,
    'vacation': 0.8,
    'tour': 0.7,
    'destination': 0.7,
    'airport': 0.7,
    'city': 0.6,
    'country': 0.6,
    'passport': 0.6,
    'itinerary': 0.5,
    'Antarctica': 0.5,
    'Asia': 0.5,
    'Cape Town': 0.5,
    'New York': 0.5,
    'Miami': 0.5,
  },
  'Politics': {
    'politics': 1,
    'government': 0.9,
    'election': 0.9,
    'vote': 0.8,
    'congress': 0.8,
    'senate': 0.8,
    'president': 0.8,
    'law': 0.7,
    'policy': 0.7,
    'Trump': 0.6,
    'Obama': 0.6,
    'Texas State': 0.5,
    'House': 0.5,
    'G.O.P.': 0.5,
  },
  'People': {
    'person': 1,
    'people': 1,
    'name': 0.9,
    'author': 0.8,
    'artist': 0.8,
    'athlete': 0.8,
    'celebrity': 0.7,
    'Jake Ellison': 0.6,
    'Trump': 0.6,
    'Obama': 0.6,
    'Messi': 0.6,
    'Katie Ledecky': 0.6,
    'Alyce McFadden': 0.5,
    'Janie Osborne': 0.5,
    'Miriam Jordan': 0.5,
  },
  'News': {
    'news': 1,
    'headline': 0.9,
    'report': 0.9,
    'article': 0.8,
    'journalist': 0.8,
    'media': 0.8,
    'press': 0.7,
    'update': 0.7,
    'The New York Times': 0.6,
    'USA TODAY': 0.6,
    'ESPN': 0.5,
    'NFL': 0.5,
    'MLB': 0.5,
    'WWE': 0.5,
  },
  'Uncategorized': {},
};
